# API Football Code
### Introduction
For the work on proving Bolivian teams outplay their opponents due to altitude difference I need to find
- All Libertadores fixtures including Bolivian teams vs Non-Bolivian Teams
- Venue of home and away leg
- Altitude of venue
- Scores

I think most of this can be done from the fixtures endpoint. It will be especially interesting to contrast first half and second half performance

In [20]:
import json
import http.client
import os
from dotenv import load_dotenv
import requests
import time
import pandas as pd

In [3]:
load_dotenv()
FB_API_KEY = os.getenv("API_FOOTBALL_KEY")

In [6]:
# setup API Connection
conn = http.client.HTTPSConnection("v3.football.api-sports.io")

HEADERS = {
    "Accept":           "application/json",
    "x-apisports-key":  FB_API_KEY,
}

conn.request("GET", "/fixtures?id=215662", headers=HEADERS)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"get":"fixtures","parameters":{"id":"215662"},"errors":[],"results":1,"paging":{"current":1,"total":1},"response":[{"fixture":{"id":215662,"referee":"H. Mastr\u00e1ngelo","timezone":"UTC","date":"2019-10-20T14:00:00+00:00","timestamp":1571580000,"periods":{"first":1571580000,"second":1571583600},"venue":{"id":33,"name":"Estadio Jos\u00e9 Mar\u00eda Minella","city":"Mar del Plata, Provincia de Buenos Aires"},"status":{"long":"Match Finished","short":"FT","elapsed":90,"extra":null}},"league":{"id":128,"name":"Liga Profesional Argentina","country":"Argentina","logo":"https:\/\/media.api-sports.io\/football\/leagues\/128.png","flag":"https:\/\/media.api-sports.io\/flags\/ar.svg","season":2019,"round":"Regular Season - 10","standings":true},"teams":{"home":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png","winner":true},"away":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png","winner":false}},"goals":{"home":1,"away":0},"score":{"halftime":{"home":1,"away":0},"fulltime":{"home":1,"away":0},"extratime":{"home":null,"away":null},"penalty":{"home":null,"away":null}},"events":[{"time":{"elapsed":25,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6126,"name":"F. Andrada"},"assist":{"id":null,"name":null},"type":"Goal","detail":"Normal Goal","comments":null},{"time":{"elapsed":33,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":5936,"name":"Julio Gonz\u00e1lez"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":33,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6126,"name":"Federico Andrada"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":36,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":5931,"name":"Diego Rodr\u00edguez"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":39,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":5954,"name":"Fernando M\u00e1rquez"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":44,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6262,"name":"Emanuel I\u00f1iguez"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":46,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":35695,"name":"D. Rodr\u00edguez"},"assist":{"id":5947,"name":"B. Merlini"},"type":"subst","detail":"Substitution 1","comments":null},{"time":{"elapsed":62,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6093,"name":"Gonzalo Ver\u00f3n"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":73,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":5942,"name":"A. Castro"},"assist":{"id":6059,"name":"G. Mainero"},"type":"subst","detail":"Substitution 2","comments":null},{"time":{"elapsed":74,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6561,"name":"N. Sol\u00eds"},"assist":{"id":35845,"name":"H. Burbano"},"type":"subst","detail":"Substitution 1","comments":null},{"time":{"elapsed":75,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6093,"name":"G. Ver\u00f3n"},"assist":{"id":6396,"name":"N. Bazzana"},"type":"subst","detail":"Substitution 2","comments":null},{"time":{"elapsed":79,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":6474,"name":"G. Gil"},"assist":{"id":6550,"name":"F. Grahl"},"type":"subst","detail":"Substitution 3","comments":null},{"time":{"elapsed":79,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":5936,"name":"J. Gonz\u00e1lez"},"assist":{"id":70767,"name":"B. Ojeda"},"type":"subst","detail":"Substitution 3","comments":null},{"time":{"elapsed":84,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":6540,"name":"Juan Rodriguez"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":85,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":35845,"name":"Hern\u00e1n Burbano"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":90,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":35845,"name":"Hern\u00e1n Burbano"},"assist":{"id":null,"name":null},"type":"Card","detail":"Red Card","comments":null},{"time":{"elapsed":90,"extra":null},"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"player":{"id":5912,"name":"Neri Cardozo"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null},{"time":{"elapsed":90,"extra":null},"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"player":{"id":35845,"name":"Hern\u00e1n Burbano"},"assist":{"id":null,"name":null},"type":"Card","detail":"Yellow Card","comments":null}],"lineups":[{"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png","colors":null},"coach":{"id":3946,"name":"G. Hoyos","photo":"https:\/\/media.api-sports.io\/football\/coachs\/3946.png"},"formation":"4-3-3","startXI":[{"player":{"id":6258,"name":"L. Pocrnjic","number":1,"pos":"G","grid":"1:1"}},{"player":{"id":6261,"name":"L. Galeano","number":6,"pos":"D","grid":"2:4"}},{"player":{"id":52701,"name":"M. Miers","number":19,"pos":"D","grid":"2:3"}},{"player":{"id":6268,"name":"L. Villalba","number":23,"pos":"D","grid":"2:2"}},{"player":{"id":6262,"name":"E. I\u00f1\u00edguez","number":21,"pos":"D","grid":"2:1"}},{"player":{"id":6474,"name":"G. Gil","number":5,"pos":"M","grid":"3:3"}},{"player":{"id":6269,"name":"F. Acevedo","number":8,"pos":"M","grid":"3:2"}},{"player":{"id":6212,"name":"L. Maciel","number":33,"pos":"M","grid":"3:1"}},{"player":{"id":6093,"name":"G. Ver\u00f3n","number":29,"pos":"F","grid":"4:3"}},{"player":{"id":6126,"name":"F. Andrada","number":10,"pos":"F","grid":"4:2"}},{"player":{"id":6561,"name":"N. Sol\u00eds","number":7,"pos":"F","grid":"4:1"}}],"substitutes":[{"player":{"id":35845,"name":"H. Burbano","number":11,"pos":"M","grid":null}},{"player":{"id":6396,"name":"N. Bazzana","number":27,"pos":"D","grid":null}},{"player":{"id":6550,"name":"F. Grahl","number":22,"pos":"M","grid":null}},{"player":{"id":152779,"name":"F. Tobares","number":40,"pos":"F","grid":null}},{"player":{"id":6255,"name":"F. Assmann","number":35,"pos":"G","grid":null}},{"player":{"id":6399,"name":"F. Evangelista","number":20,"pos":"D","grid":null}},{"player":{"id":5426,"name":"C. Fara","number":2,"pos":"D","grid":null}}]},{"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png","colors":null},"coach":{"id":896,"name":"M. Soso","photo":"https:\/\/media.api-sports.io\/football\/coachs\/896.png"},"formation":"4-4-2","startXI":[{"player":{"id":5932,"name":"E. Unsain","number":22,"pos":"G","grid":"1:1"}},{"player":{"id":5935,"name":"R. Delgado","number":33,"pos":"D","grid":"2:4"}},{"player":{"id":6540,"name":"J. Rodr\u00edguez","number":28,"pos":"D","grid":"2:3"}},{"player":{"id":5936,"name":"J. Gonz\u00e1lez","number":4,"pos":"D","grid":"2:2"}},{"player":{"id":5991,"name":"H. Mart\u00ednez","number":21,"pos":"D","grid":"2:1"}},{"player":{"id":5912,"name":"N. Cardozo","number":10,"pos":"M","grid":"3:4"}},{"player":{"id":35695,"name":"D. Rodr\u00edguez","number":15,"pos":null,"grid":"3:3"}},{"player":{"id":6619,"name":"R. Loaiza","number":30,"pos":"M","grid":"3:2"}},{"player":{"id":5942,"name":"A. Castro","number":11,"pos":"M","grid":"3:1"}},{"player":{"id":5954,"name":"F. M\u00e1rquez","number":9,"pos":"F","grid":"4:2"}},{"player":{"id":5952,"name":"N. Fern\u00e1ndez","number":29,"pos":"F","grid":"4:1"}}],"substitutes":[{"player":{"id":5947,"name":"B. Merlini","number":7,"pos":"M","grid":null}},{"player":{"id":6059,"name":"G. Mainero","number":8,"pos":"M","grid":null}},{"player":{"id":70767,"name":"B. Ojeda","number":26,"pos":"M","grid":null}},{"player":{"id":9515,"name":"M. Ben\u00edtez","number":3,"pos":"D","grid":null}},{"player":{"id":5929,"name":"N. Avellaneda","number":17,"pos":"G","grid":null}},{"player":{"id":5943,"name":"F. Cerro","number":18,"pos":"M","grid":null}},{"player":{"id":6433,"name":"G. Piovi","number":16,"pos":"D","grid":null}}]}],"statistics":[{"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png"},"statistics":[{"type":"Shots on Goal","value":3},{"type":"Shots off Goal","value":2},{"type":"Total Shots","value":9},{"type":"Blocked Shots","value":4},{"type":"Shots insidebox","value":4},{"type":"Shots outsidebox","value":5},{"type":"Fouls","value":22},{"type":"Corner Kicks","value":3},{"type":"Offsides","value":1},{"type":"Ball Possession","value":"32%"},{"type":"Yellow Cards","value":5},{"type":"Red Cards","value":1},{"type":"Goalkeeper Saves","value":0},{"type":"Total passes","value":242},{"type":"Passes accurate","value":121},{"type":"Passes %","value":"50%"}]},{"team":{"id":442,"name":"Defensa Y Justicia","logo":"https:\/\/media.api-sports.io\/football\/teams\/442.png"},"statistics":[{"type":"Shots on Goal","value":0},{"type":"Shots off Goal","value":3},{"type":"Total Shots","value":7},{"type":"Blocked Shots","value":4},{"type":"Shots insidebox","value":4},{"type":"Shots outsidebox","value":3},{"type":"Fouls","value":10},{"type":"Corner Kicks","value":5},{"type":"Offsides","value":9},{"type":"Ball Possession","value":"68%"},{"type":"Yellow Cards","value":5},{"type":"Red Cards","value":0},{"type":"Goalkeeper Saves","value":2},{"type":"Total passes","value":514},{"type":"Passes accurate","value":397},{"type":"Passes %","value":"77%"}]}],"players":[{"team":{"id":463,"name":"Aldosivi","logo":"https:\/\/media.api-sports.io\/football\/teams\/463.png","update":"2020-05-13T18:19:45+00:00"},"players":[{"player":{"id":6258,"name":"Luciano Pocrnjic","photo":"https:\/\/media.api-sports.io\/football\/players\/6258.png"},"statistics":[{"games":{"minutes":90,"number":1,"position":"G","rating":"7.1","captain":true,"substitute":false},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":0},"passes":{"total":13,"key":0,"accuracy":"44%"},"tackles":{"total":null,"blocks":0,"interceptions":0},"duels":{"total":null,"won":null},"dribbles":{"attempts":0,"success":0,"past":null},"fouls":{"drawn":0,"committed":0},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":0}}]},{"player":{"id":6262,"name":"Emanuel I\u00f1iguez","photo":"https:\/\/media.api-sports.io\/football\/players\/6262.png"},"statistics":[{"games":{"minutes":90,"number":21,"position":"D","rating":"7.0","captain":false,"substitute":false},"offsides":null,"shots":{"total":1,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":8,"key":1,"accuracy":"34%"},"tackles":{"total":3,"blocks":0,"interceptions":0},"duels":{"total":null,"won":null},"dribbles":{"attempts":0,"success":0,"past":1},"fouls":{"drawn":1,"committed":1},"cards":{"yellow":1,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6261,"name":"Leonel Galeano","photo":"https:\/\/media.api-sports.io\/football\/players\/6261.png"},"statistics":[{"games":{"minutes":90,"number":6,"position":"D","rating":"7.6","captain":false,"substitute":false},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":9,"key":0,"accuracy":"50%"},"tackles":{"total":3,"blocks":3,"interceptions":2},"duels":{"total":null,"won":null},"dribbles":{"attempts":0,"success":0,"past":2},"fouls":{"drawn":1,"committed":0},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":52701,"name":"Marcos Miers","photo":"https:\/\/media.api-sports.io\/football\/players\/52701.png"},"statistics":[{"games":{"minutes":90,"number":19,"position":"D","rating":"7.2","captain":false,"substitute":false},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":6,"key":0,"accuracy":"46%"},"tackles":{"total":1,"blocks":1,"interceptions":1},"duels":{"total":null,"won":null},"dribbles":{"attempts":1,"success":1,"past":null},"fouls":{"drawn":0,"committed":1},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6268,"name":"Lucas Villalba","photo":"https:\/\/media.api-sports.io\/football\/players\/6268.png"},"statistics":[{"games":{"minutes":90,"number":23,"position":"D","rating":"7.0","captain":false,"substitute":false},"offsides":null,"shots":{"total":2,"on":1},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":5,"key":1,"accuracy":"21%"},"tackles":{"total":1,"blocks":0,"interceptions":6},"duels":{"total":null,"won":null},"dribbles":{"attempts":2,"success":2,"past":1},"fouls":{"drawn":0,"committed":3},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6212,"name":"Leandro Maciel","photo":"https:\/\/media.api-sports.io\/football\/players\/6212.png"},"statistics":[{"games":{"minutes":90,"number":33,"position":"M","rating":"6.4","captain":false,"substitute":false},"offsides":null,"shots":{"total":1,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":14,"key":0,"accuracy":"60%"},"tackles":{"total":null,"blocks":0,"interceptions":1},"duels":{"total":null,"won":null},"dribbles":{"attempts":2,"success":2,"past":3},"fouls":{"drawn":0,"committed":1},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6474,"name":"Gaston Gil Romero","photo":"https:\/\/media.api-sports.io\/football\/players\/6474.png"},"statistics":[{"games":{"minutes":79,"number":5,"position":"M","rating":"6.6","captain":false,"substitute":false},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":7,"key":0,"accuracy":"38%"},"tackles":{"total":4,"blocks":0,"interceptions":1},"duels":{"total":null,"won":null},"dribbles":{"attempts":2,"success":0,"past":null},"fouls":{"drawn":0,"committed":5},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6269,"name":"Federico Gino","photo":"https:\/\/media.api-sports.io\/football\/players\/6269.png"},"statistics":[{"games":{"minutes":90,"number":8,"position":"M","rating":"6.9","captain":false,"substitute":false},"offsides":null,"shots":{"total":1,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":19,"key":1,"accuracy":"65%"},"tackles":{"total":2,"blocks":0,"interceptions":2},"duels":{"total":null,"won":null},"dribbles":{"attempts":3,"success":2,"past":1},"fouls":{"drawn":1,"committed":2},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6093,"name":"Gonzalo Ver\u00f3n","photo":"https:\/\/media.api-sports.io\/football\/players\/6093.png"},"statistics":[{"games":{"minutes":75,"number":29,"position":"F","rating":"6.2","captain":false,"substitute":false},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":12,"key":0,"accuracy":"66%"},"tackles":{"total":null,"blocks":0,"interceptions":1},"duels":{"total":null,"won":null},"dribbles":{"attempts":1,"success":0,"past":1},"fouls":{"drawn":1,"committed":2},"cards":{"yellow":1,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6126,"name":"Federico Andrada","photo":"https:\/\/media.api-sports.io\/football\/players\/6126.png"},"statistics":[{"games":{"minutes":90,"number":10,"position":"F","rating":"6.7","captain":false,"substitute":false},"offsides":null,"shots":{"total":3,"on":2},"goals":{"total":1,"conceded":0,"assists":null,"saves":null},"passes":{"total":11,"key":0,"accuracy":"55%"},"tackles":{"total":null,"blocks":0,"interceptions":0},"duels":{"total":null,"won":null},"dribbles":{"attempts":1,"success":1,"past":2},"fouls":{"drawn":2,"committed":2},"cards":{"yellow":1,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6561,"name":"Nazareno Solis","photo":"https:\/\/media.api-sports.io\/football\/players\/6561.png"},"statistics":[{"games":{"minutes":74,"number":7,"position":"F","rating":"7.1","captain":false,"substitute":false},"offsides":null,"shots":{"total":1,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":11,"key":0,"accuracy":"61%"},"tackles":{"total":2,"blocks":0,"interceptions":1},"duels":{"total":null,"won":null},"dribbles":{"attempts":1,"success":1,"past":1},"fouls":{"drawn":1,"committed":2},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6396,"name":"Nicol\u00e1s Bazzana","photo":"https:\/\/media.api-sports.io\/football\/players\/6396.png"},"statistics":[{"games":{"minutes":15,"number":27,"position":"D","rating":"6.5","captain":false,"substitute":true},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":0,"key":0,"accuracy":"0%"},"tackles":{"total":null,"blocks":0,"interceptions":0},"duels":{"total":null,"won":null},"dribbles":{"attempts":0,"success":0,"past":null},"fouls":{"drawn":0,"committed":1},"cards":{"yellow":0,"red":0},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":35845,"name":"Hern\u00e1n Burbano","photo":"https:\/\/media.api-sports.io\/football\/players\/35845.png"},"statistics":[{"games":{"minutes":15,"number":11,"position":"M","rating":"3.7","captain":false,"substitute":true},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":null,"conceded":0,"assists":null,"saves":null},"passes":{"total":2,"key":0,"accuracy":"40%"},"tackles":{"total":null,"blocks":0,"interceptions":0},"duels":{"total":null,"won":null},"dribbles":{"attempts":1,"success":1,"past":null},"fouls":{"drawn":2,"committed":1},"cards":{"yellow":2,"red":1},"penalty":{"won":null,"commited":null,"scored":0,"missed":0,"saved":null}}]},{"player":{"id":6550,"name":"Francisco Grahl","photo":"https:\/\/media.api-sports.io\/football\/players\/6550.png"},"statistics":[{"games":{"minutes":11,"number":22,"position":"M","rating":"6.7","captain":false,"substitute":true},"offsides":null,"shots":{"total":0,"on":0},"goals":{"total":nu

In [32]:
# code from football API docs example
# ——— CONFIG ———
API_KEY    = FB_API_KEY
BASE_URL   = "https://v3.football.api-sports.io/fixtures"
HEADERS = {
    "Accept":           "application/json",
    "x-apisports-key":  API_KEY,
}
LEAGUE_ID  = 13     # e.g. Premier League
SEASON     = 2021   # e.g. 2024
# Only completed ("FT","AET","PEN") + in‑progress ("1H","HT","2H","ET","BT","P")
STATUS     = "FT"
CHUNK_SIZE = 20     # max fixture IDs per call :contentReference[oaicite:2]{index=2}

In [33]:
def chunk_list(lst, size):
    """Split list into chunks of at most `size`."""
    return [lst[i:i+size] for i in range(0, len(lst), size)]

def fetch_fixture_ids():
    """Return a list of fixture IDs for the given league/season/status."""
    params = {
        "league": LEAGUE_ID,
        "season": SEASON,
        "status": STATUS
    }
    resp = requests.get(BASE_URL, headers=HEADERS, params=params)
    print(resp.status_code, resp.headers.get("content-type"))
    #print(resp.text)
    resp.raise_for_status()
    fixtures = resp.json().get("response", [])
    return [f["fixture"]["id"] for f in fixtures if "fixture" in f]

In [34]:
fixture_ids = fetch_fixture_ids()
chunks = chunk_list(fixture_ids, CHUNK_SIZE)
print(f"Will retrieve {len(fixture_ids)} fixtures in {len(chunks)} batches.")

200 application/json
Will retrieve 149 fixtures in 8 batches.

In [35]:
def fetch_fixtures_by_ids(id_group):
    """Fetch full fixture data for a hyphen‑joined group of IDs."""
    ids_param = "-".join(str(i) for i in id_group)
    resp = requests.get(
        BASE_URL,
        headers=HEADERS,
        params={"ids": ids_param}
    )
    resp = requests.get(BASE_URL, headers=HEADERS, params={"ids": ids_param})
    print(resp.status_code, resp.request.url)
    #print(resp.text)   # or resp.json()
    resp.raise_for_status()
    return resp.json().get("response", [])

all_data_2021 = []
for group in chunks:
    batch = fetch_fixtures_by_ids(group)
    all_data_2022.extend(batch)
    time.sleep(1)  # crude rate‑limit guard; adjust as needed :contentReference[oaicite:3]{index=3}

print(f"Retrieved detailed data for {len(all_data_2023)} fixtures.")

200 https://v3.football.api-sports.io/fixtures?ids=819350-819348-819352-819351-819353-819340-819344-842760-828392-819342-842762-819346-842764-819341-842761-828393-819343-819347-842763-842765
200 https://v3.football.api-sports.io/fixtures?ids=846333-846336-846331-846335-846334-846337-853677-853676-853675-853679-853678-853680-853682-853683-853681-853685-853686-853684-853687-853688
200 https://v3.football.api-sports.io/fixtures?ids=853689-853690-853691-853692-853693-853694-853696-853695-853697-853698-853702-853699-853701-853700-853703-853704-853705-853706-853709-853710
200 https://v3.football.api-sports.io/fixtures?ids=853708-853707-853712-853713-853711-853714-853718-853716-853715-853717-853719-853720-853721-853722-853723-853724-853725-853728-853727-853726
200 https://v3.football.api-sports.io/fixtures?ids=853729-853730-853731-853733-853732-853734-853735-853736-853737-853738-853740-853741-853739-853743-853742-853744-853745-853746-853749-853747
200 https://v3.football.api-sports.io/fixtures?ids=853750-853748-853751-853752-853753-853754-853756-853755-853757-853759-853758-853760-853761-853762-853763-853764-853766-853765-853767-853768
200 https://v3.football.api-sports.io/fixtures?ids=853770-853769-863097-863103-863107-863101-863099-863095-863093-863105-863098-863108-863100-863102-863094-863096-863106-885347-885349-885351
200 https://v3.football.api-sports.io/fixtures?ids=885345-885348-885350-885346-933774-933776-933775-933777-958842
Retrieved detailed data for 149 fixtures.

In [36]:
all_data_2022[1]

{'fixture': {'id': 819341,
  'referee': 'G. Vargas',
  'timezone': 'UTC',
  'date': '2022-02-28T22:15:00+00:00',
  'timestamp': 1646086500,
  'periods': {'first': 1646086500, 'second': 1646090100},
  'venue': {'id': 1660,
   'name': 'Estadio Monumental de Maturín',
   'city': 'Maturín'},
  'status': {'long': 'Match Finished',
   'short': 'FT',
   'elapsed': 90,
   'extra': None}},
 'league': {'id': 13,
  'name': 'CONMEBOL Libertadores',
  'country': 'World',
  'logo': 'https://media.api-sports.io/football/leagues/13.png',
  'flag': None,
  'season': 2022,
  'round': '2nd Round',
  'standings': True},
 'teams': {'home': {'id': 2811,
   'name': 'Monagas SC',
   'logo': 'https://media.api-sports.io/football/teams/2811.png',
   'winner': True},
  'away': {'id': 2325,
   'name': 'Everton de Vina',
   'logo': 'https://media.api-sports.io/football/teams/2325.png',
   'winner': False}},
 'goals': {'home': 1, 'away': 0},
 'score': {'halftime': {'home': 0, 'away': 0},
  'fulltime': {'home': 1, 'away': 0},
  'extratime': {'home': None, 'away': None},
  'penalty': {'home': None, 'away': None}},
 'events': [{'time': {'elapsed': 2, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 129951, 'name': 'David Zalzman'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Yellow Card',
   'comments': 'Foul'},
  {'time': {'elapsed': 37, 'extra': None},
   'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png'},
   'player': {'id': 11530, 'name': 'Diego Oyarzún'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Yellow Card',
   'comments': 'Foul'},
  {'time': {'elapsed': 46, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 16362, 'name': 'O. González'},
   'assist': {'id': None, 'name': None},
   'type': 'Goal',
   'detail': 'Normal Goal',
   'comments': None},
  {'time': {'elapsed': 53, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 57801, 'name': 'Azmahar Ariano'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Yellow Card',
   'comments': 'Foul'},
  {'time': {'elapsed': 57, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 57801, 'name': 'A. Ariano'},
   'assist': {'id': 356814, 'name': 'D. Martínez'},
   'type': 'subst',
   'detail': 'Substitution 2',
   'comments': None},
  {'time': {'elapsed': 64, 'extra': None},
   'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png'},
   'player': {'id': 11648, 'name': 'P. Sánchez'},
   'assist': {'id': 11676, 'name': 'C. Valenzuela'},
   'type': 'subst',
   'detail': 'Substitution 1',
   'comments': None},
  {'time': {'elapsed': 66, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 52471, 'name': 'E. Navas'},
   'assist': {'id': 52543, 'name': 'L. Guerra'},
   'type': 'subst',
   'detail': 'Substitution 5',
   'comments': None},
  {'time': {'elapsed': 66, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 57805, 'name': 'I. Anderson'},
   'assist': {'id': 52501, 'name': 'K. Barreto'},
   'type': 'subst',
   'detail': 'Substitution 6',
   'comments': None},
  {'time': {'elapsed': 66, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 52556, 'name': 'F. González'},
   'assist': {'id': 52519, 'name': 'Y. Montero'},
   'type': 'subst',
   'detail': 'Substitution 7',
   'comments': None},
  {'time': {'elapsed': 71, 'extra': None},
   'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png'},
   'player': {'id': 35671, 'name': 'I. Sosa'},
   'assist': {'id': 195801, 'name': 'C. Medina'},
   'type': 'subst',
   'detail': 'Substitution 2',
   'comments': None},
  {'time': {'elapsed': 78, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 52543, 'name': 'Luis Guerra'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Red Card',
   'comments': 'Violent conduct'},
  {'time': {'elapsed': 84, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 52519, 'name': 'Yeangel Emilio Montero Manzano'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Yellow Card',
   'comments': 'Foul'},
  {'time': {'elapsed': 84, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 50911, 'name': 'C. Martínez'},
   'assist': {'id': 197660, 'name': 'E. Carrión'},
   'type': 'subst',
   'detail': 'Substitution 10',
   'comments': None},
  {'time': {'elapsed': 88, 'extra': None},
   'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'player': {'id': 159161, 'name': 'Andrés Romero'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Yellow Card',
   'comments': 'Foul'},
  {'time': {'elapsed': 90, 'extra': 3},
   'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png'},
   'player': {'id': 11676, 'name': 'César Valenzuela'},
   'assist': {'id': None, 'name': None},
   'type': 'Card',
   'detail': 'Yellow Card',
   'comments': 'Foul'},
  {'time': {'elapsed': 90, 'extra': None},
   'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png'},
   'player': {'id': 11630, 'name': 'A. Ibacache'},
   'assist': {'id': 11631, 'name': 'J. López'},
   'type': 'subst',
   'detail': 'Substitution 7',
   'comments': None}],
 'lineups': [{'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png',
    'colors': {'player': {'primary': '373d88',
      'number': 'f3eded',
      'border': '000000'},
     'goalkeeper': {'primary': '000000',
      'number': 'ffffff',
      'border': '000000'}}},
   'coach': {'id': 2823,
    'name': 'J. Ferreira',
    'photo': 'https://media.api-sports.io/football/coachs/2823.png'},
   'formation': '4-4-2',
   'startXI': [{'player': {'id': 58959,
      'name': 'N. Caprio',
      'number': 1,
      'pos': 'G',
      'grid': '1:1'}},
    {'player': {'id': 52539,
      'name': 'G. Perozo',
      'number': 20,
      'pos': 'D',
      'grid': '2:4'}},
    {'player': {'id': 57801,
      'name': 'A. Ariano',
      'number': 6,
      'pos': 'D',
      'grid': '2:3'}},
    {'player': {'id': 52168,
      'name': 'G. Dolgetta',
      'number': 13,
      'pos': 'D',
      'grid': '2:2'}},
    {'player': {'id': 16362,
      'name': 'O. González',
      'number': 19,
      'pos': 'M',
      'grid': '2:1'}},
    {'player': {'id': 57805,
      'name': 'I. Anderson',
      'number': 3,
      'pos': 'D',
      'grid': '3:4'}},
    {'player': {'id': 129951,
      'name': 'D. Zalzman',
      'number': 8,
      'pos': 'M',
      'grid': '3:3'}},
    {'player': {'id': 50911,
      'name': 'C. Martínez',
      'number': 15,
      'pos': 'M',
      'grid': '3:2'}},
    {'player': {'id': 52471,
      'name': 'E. Navas',
      'number': 26,
      'pos': 'F',
      'grid': '3:1'}},
    {'player': {'id': 159161,
      'name': 'A. Romero',
      'number': 29,
      'pos': 'M',
      'grid': '4:2'}},
    {'player': {'id': 52556,
      'name': 'F. González',
      'number': 18,
      'pos': 'F',
      'grid': '4:1'}}],
   'substitutes': [{'player': {'id': 356814,
      'name': 'D. Martínez',
      'number': 30,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 52543,
      'name': 'L. Guerra',
      'number': 10,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 52501,
      'name': 'K. Barreto',
      'number': 28,
      'pos': 'F',
      'grid': None}},
    {'player': {'id': 52519,
      'name': 'Y. Montero',
      'number': 7,
      'pos': 'F',
      'grid': None}},
    {'player': {'id': 197660,
      'name': 'E. Carrión',
      'number': 16,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 52503,
      'name': 'K. De Vasconcelos',
      'number': 24,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 52126,
      'name': 'E. Martínez',
      'number': 5,
      'pos': 'D',
      'grid': None}},
    {'player': {'id': 52627,
      'name': 'A. Moreno',
      'number': 4,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 11681,
      'name': 'A. Blondell',
      'number': 17,
      'pos': 'F',
      'grid': None}},
    {'player': {'id': 52774,
      'name': 'J. Roa',
      'number': 12,
      'pos': 'G',
      'grid': None}},
    {'player': {'id': 52640,
      'name': 'J. Calzadilla',
      'number': 27,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 52668,
      'name': 'O. Jiménez',
      'number': 22,
      'pos': 'D',
      'grid': None}}]},
  {'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png',
    'colors': {'player': {'primary': 'fdf235',
      'number': '0000a0',
      'border': 'ff0000'},
     'goalkeeper': {'primary': 'ff0000',
      'number': 'ffffff',
      'border': 'ff0000'}}},
   'coach': {'id': 508,
    'name': 'F. Meneghini',
    'photo': 'https://media.api-sports.io/football/coachs/508.png'},
   'formation': '3-4-3',
   'startXI': [{'player': {'id': 11818,
      'name': 'F. De Paul',
      'number': 30,
      'pos': 'G',
      'grid': '1:1'}},
    {'player': {'id': 11530,
      'name': 'D. Oyarzún',
      'number': 24,
      'pos': 'D',
      'grid': '2:3'}},
    {'player': {'id': 11630,
      'name': 'A. Ibacache',
      'number': 4,
      'pos': 'M',
      'grid': '2:2'}},
    {'player': {'id': 11643,
      'name': 'Á. Madrid',
      'number': 6,
      'pos': 'M',
      'grid': '2:1'}},
    {'player': {'id': 11828,
      'name': 'R. Echeverría',
      'number': 20,
      'pos': 'D',
      'grid': '3:4'}},
    {'player': {'id': 11638,
      'name': 'B. Berríos',
      'number': 21,
      'pos': 'M',
      'grid': '3:3'}},
    {'player': {'id': 11646,
      'name': 'S. Pereira',
      'number': 26,
      'pos': 'D',
      'grid': '3:2'}},
    {'player': {'id': 5978,
      'name': 'A. Sánchez',
      'number': 16,
      'pos': 'M',
      'grid': '3:1'}},
    {'player': {'id': 35671,
      'name': 'I. Sosa',
      'number': 18,
      'pos': 'F',
      'grid': '4:3'}},
    {'player': {'id': 11648,
      'name': 'P. Sánchez',
      'number': 19,
      'pos': 'F',
      'grid': '4:2'}},
    {'player': {'id': 16265,
      'name': 'L. Di Yorio',
      'number': 7,
      'pos': 'F',
      'grid': '4:1'}}],
   'substitutes': [{'player': {'id': 11676,
      'name': 'C. Valenzuela',
      'number': 8,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 195801,
      'name': 'C. Medina',
      'number': 14,
      'pos': 'D',
      'grid': None}},
    {'player': {'id': 11631,
      'name': 'J. López',
      'number': 28,
      'pos': 'D',
      'grid': None}},
    {'player': {'id': 345020,
      'name': 'D. Vera',
      'number': 25,
      'pos': 'D',
      'grid': None}},
    {'player': {'id': 345605,
      'name': 'E. Arismendi',
      'number': 29,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 330232,
      'name': 'R. Díaz',
      'number': 27,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 277977,
      'name': 'G. Moya',
      'number': 17,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 125667,
      'name': 'J. Peña',
      'number': 12,
      'pos': 'G',
      'grid': None}},
    {'player': {'id': 12090,
      'name': 'F. Saavedra',
      'number': 23,
      'pos': 'M',
      'grid': None}},
    {'player': {'id': 325833,
      'name': 'M. Wassenne',
      'number': 35,
      'pos': 'F',
      'grid': None}},
    {'player': {'id': 237074,
      'name': 'C. Riquelme',
      'number': 2,
      'pos': 'D',
      'grid': None}}]}],
 'statistics': [{'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png'},
   'statistics': [{'type': 'Shots on Goal', 'value': 4},
    {'type': 'Shots off Goal', 'value': 9},
    {'type': 'Total Shots', 'value': 18},
    {'type': 'Blocked Shots', 'value': 5},
    {'type': 'Shots insidebox', 'value': 7},
    {'type': 'Shots outsidebox', 'value': 11},
    {'type': 'Fouls', 'value': 17},
    {'type': 'Corner Kicks', 'value': 5},
    {'type': 'Offsides', 'value': 0},
    {'type': 'Ball Possession', 'value': '50%'},
    {'type': 'Yellow Cards', 'value': 4},
    {'type': 'Red Cards', 'value': 1},
    {'type': 'Goalkeeper Saves', 'value': 1},
    {'type': 'Total passes', 'value': 437},
    {'type': 'Passes accurate', 'value': 344},
    {'type': 'Passes %', 'value': '79%'}]},
  {'team': {'id': 2325,
    'name': 'Everton de Vina',
    'logo': 'https://media.api-sports.io/football/teams/2325.png'},
   'statistics': [{'type': 'Shots on Goal', 'value': 1},
    {'type': 'Shots off Goal', 'value': 2},
    {'type': 'Total Shots', 'value': 5},
    {'type': 'Blocked Shots', 'value': 2},
    {'type': 'Shots insidebox', 'value': 4},
    {'type': 'Shots outsidebox', 'value': 1},
    {'type': 'Fouls', 'value': 14},
    {'type': 'Corner Kicks', 'value': 0},
    {'type': 'Offsides', 'value': 3},
    {'type': 'Ball Possession', 'value': '50%'},
    {'type': 'Yellow Cards', 'value': 2},
    {'type': 'Red Cards', 'value': 0},
    {'type': 'Goalkeeper Saves', 'value': 3},
    {'type': 'Total passes', 'value': 447},
    {'type': 'Passes accurate', 'value': 353},
    {'type': 'Passes %', 'value': '79%'}]}],
 'players': [{'team': {'id': 2811,
    'name': 'Monagas SC',
    'logo': 'https://media.api-sports.io/football/teams/2811.png',
    'update': '2022-10-31T04:25:41+00:00'},
   'players': [{'player': {'id': 58959,
      'name': 'Nicolás Caprio',
      'photo': 'https://media.api-sports.io/football/players/58959.png'},
     'statistics': [{'games': {'minutes': 96,
        'number': 1,
        'position': 'G',
        'rating': '7.2',
        'captain': False,
        'substitute': False},
       'offsides': None,
       'shots': {'total': None, 'on': None},
       'goals': {'total': None, 'conceded': 0, 'assists': None, 'saves': 1},
       'passes': {'total': 14, 'key': None, 'accuracy': '11'},
       'tackles': {'total': None, 'blocks': None, 'interceptions': None},
       'duels': {'total': 3, 'won': 3},
       'dribbles': {'attempts': None, 'success': None, 'past': None},
       'fouls': {'drawn': None, 'committed': None},
       'cards': {'yellow': 0, 'red': 0},
       'penalty': {'won': None,
        'commited': None,
        'scored': 0,
        'missed': 0,
        'saved': 0}}]},
    {'player': {'id': 57805,
      'name': 'Iván Anderson',
      'photo': 'https://media.api-sports.io/football/players/57805.png'},
     'statistics': [{'games': {'minutes': 66,
        'number': 3,
        'position': 'D',
        'rating': '6.3',
        'captain': False,
        'substitute': False},
       'offsides': None,
       'shots': {'total': None, 'on': None},
       'goals': {'total': None, 'conceded': 0, 'assists': None, 'saves': None},
       'passes': {'total': 33, 'key': None, 'accuracy': '24'},
       'tackles': {'total': None, 'blocks': None, 'interceptions': 4},
       'duels': {'total': 5, 'won': 1},
       'dribbles': {'attempts': None, 'success': None, 'past': 1},
       'fouls': {'drawn': None, 'committed': 1},
       'cards': {'yellow': 0, 'red': 0},
       'penalty': {'won': None,
        'commited': None,
        'scored': 0,
        'missed': 0,
        'saved': None}}]},
    {'player': {'id': 52168,
      'name': 'Giovanni Dolgetta',
      'photo': 'https://media.api-sports.io/football/players/52168.png'},
     'statistics': [{'games': {'minutes': 96,
        'number': 13,
        'position': 'D',
        'rating': '7.2',
        'captain': False,
        'substitute': False},
       'offsides': None,
       'shots': {'total': None, 'on': None},
       'goals': {'total': None, 'conceded': 0, 'assists': None, 'saves': None},
       'passes': {'total': 40, 'key': 1, 'accuracy': '28'},
       'tackles': {'total': None, 'blocks': None, 'interceptions': 3},
       'duels': {'total': 15, 'won': 9},
       'dribbles': {'attempts': 2, 'success': 2, 'past': None},
       'fouls': {'drawn': 1, 'committed': 3},
       'cards': {'yellow': 0, 'red': 0},
       'penalty': {'won': None,
        'commited': None,
        'scored': 0,
        'missed': 0,
        'saved': None}}]},
    {'player': {'id': 52539,
      'name': 'Grenddy Perozo',
      'photo': 'https://media.api-sports.io/football/players/52539.png'},
     'statistics': [{'games': {'minutes': 96,
        'number': 20,
        'position': 'D',
        'rating': '6.3',
        'captain': True,
        'substitute': False},
       'offsides': None,
       'shots': {'total': 1, 'on': 1},
       'goals': {'total': None, 'conceded': 0, 'assists': None, 'saves': None},
       'passes': {'total': 33, 'key': None, 'accuracy': '30'},
       'tackles': {'total': 1, 'blocks': 1, 'interceptions': 2},
       'duels': {'total': 8, 'won': 2},
       'dribbles': {'attempts': None, 'success': None, 'past': 4},
       'fouls': {'drawn': None, 'committed': None},
       'cards': {'yellow': 0, 'red': 0},
       'penalty': {'won': None,
        'commited': None,
        'scored': 0,
        'missed': 0,
        'saved': None}}]},
    {'player': {'id': 57801,
      'name': 'Azmahar Ariano',
      'photo': 'https://media.api-sports.io/football/players/57801.png'},
     'statistics': [{'games': {'minutes': 57,
        'number': 6,
        'position': 'D',
        'rating': '7.2',
        'captain': False,
        'substitute': False},
       'offsides': None,
       'shots': {'total': 1, 'on': 1},
       'goals': {'total': None, 'conceded': 0, 'assists': None, 'saves': None},
       'passes': {'total': 37, 'key': None, 'accuracy': '29'},
       'tackles': {'total': None, 'blocks': 1, 'interceptions': 1},
       'duels': {'total': 7, 'won': 3},
       'dribbles': {'attempts': None, 'success': None, 'past': None},
       'fouls': {'drawn': 2, 'committed': 2},
       'cards': {'yellow': 1, 'red': 0},
       'penalty': {'won': None,
        'commited': None,
        'scored': 0,
        'missed': 0,
        'saved': None}}]},
    {'player': {'id': 159161,
      'name': 'Andrés Romero',
      'photo': 'https://media.api-sports.io/football/players/159161.png'},
     'statistics': [{'games': {'minutes': 96,
        'number': 29,
        'position': 'M',
        'rating': '6.6',
        'captain': False,
        'substitute': False},
       'offsides': None,
       'shots': {'total': 2, 'on': None},
       'goals': {'total': None, 'conceded': 0, 'assists': None, 'saves': None},
       'passes': {'total': 44, 'key': 1, 'accuracy': '34'},
       'tackles': {'total': 3, 'blocks': None, 'interceptions': None},
       'duels': {'total': 14, 'won': 4},
       'dribbles': {'attempts': None, 'success': None, 'past': 3},
       'fouls': {'drawn': 1, 'committed': 3},
       'cards': {'yellow': 1, 'red': 0},
       'penalty': {'won': None,
        'commited': None,
        'scored': 0,

In [18]:
# pick out the relevant columns for my table

competition_name = all_data[i]['league']['id']
competition_id = all_data[i]['league']['name']
competition_season = all_data[i]['league']['season']
competition_round = all_data[i]['league']['round']
fixture_id = all_data[i]['fixture']['id']
fixture_date = all_data[i]['fixture']['date']
fixture_venue_id = all_data[i]['fixture']['venue']['id']
fixture_venue_name = all_data[i]['fixture']['venue']['name']
fixture_venue_city = all_data[i]['fixture']['venue']['city']
home_team_id = all_data[i]['teams']['home']['id']
home_team_name = all_data[i]['teams']['home']['name']
home_team_h1_goals = all_data[i]['score']['halftime']['home']
home_team_h2_goals = all_data[i]['score']['halftime']['home'] - all_data[i]['teams']['score']['halftime']['home']
home_team_ft_goals = all_data[i]['score']['fulltime']['home']
away_team_id = all_data[i]['teams']['away']['id']
away_team_name = all_data[i]['teams']['away']['name']
away_team_h1_goals = all_data[i]['score']['halftime']['away']
away_team_h2_goals = all_data[i]['score']['halftime']['away'] - all_data[i]['teams']['score']['halftime']['away']
away_team_ft_goals = all_data[i]['score']['fulltime']['away']

NameError: name 'i' is not defined

In [37]:


# Assuming all_data is your list of JSON objects
rows = []

for match in all_data_2023:
    row = {
        'competition_id': match['league']['id'],
        'competition_name': match['league']['name'],
        'competition_season': match['league']['season'],
        'competition_round': match['league']['round'],
        'fixture_id': match['fixture']['id'],
        'fixture_date': match['fixture']['date'],
        'fixture_venue_id': match['fixture']['venue']['id'],
        'fixture_venue_name': match['fixture']['venue']['name'],
        'fixture_venue_city': match['fixture']['venue']['city'],
        'home_team_id': match['teams']['home']['id'],
        'home_team_name': match['teams']['home']['name'],
        'home_team_h1_goals': match['score']['halftime']['home'],
        'home_team_h2_goals': match['score']['fulltime']['home'] - match['score']['halftime']['home'],
        'home_team_ft_goals': match['score']['fulltime']['home'],
        'away_team_id': match['teams']['away']['id'],
        'away_team_name': match['teams']['away']['name'],
        'away_team_h1_goals': match['score']['halftime']['away'],
        'away_team_h2_goals': match['score']['fulltime']['away'] - match['score']['halftime']['away'],
        'away_team_ft_goals': match['score']['fulltime']['away']
    }
    rows.append(row)

# Convert to DataFrame
df_22 = pd.DataFrame(rows)

In [22]:
df

,competition_id,competition_name,competition_season,competition_round,fixture_id,fixture_date,fixture_venue_id,fixture_venue_name,fixture_venue_city,home_team_id,home_team_name,home_team_h1_goals,home_team_h2_goals,home_team_ft_goals,away_team_id,away_team_name,away_team_h1_goals,away_team_h2_goals,away_team_ft_goals
0,13,CONMEBOL Libertadores,2024,2nd Round,1149590,2024-02-21T00:30:00+00:00,380.0,Estadio Atanasio Girardot,Medellín,1144,Rionegro Aguilas,0,0,0,794,RB Bragantino,0,0,0
1,13,CONMEBOL Libertadores,2024,2nd Round,1149592,2024-02-21T00:30:00+00:00,2487.0,Estadio Municipal El Alto,El Alto,3700,Always Ready,1,5,6,2546,Sporting Cristal,1,0,1
2,13,CONMEBOL Libertadores,2024,2nd Round,1149593,2024-02-28T00:30:00+00:00,1228.0,Estadio Nacional de Lima,Lima,2546,Sporting Cristal,1,2,3,3700,Always Ready,1,0,1
3,13,CONMEBOL Libertadores,2024,2nd Round,1149594,2024-02-23T00:30:00+00:00,80.0,Estadio Malvinas Argentinas,"Mendoza, Provincia de Mendoza",439,Godoy Cruz,0,0,0,2315,Colo Colo,0,1,1
4,13,CONMEBOL Libertadores,2024,2nd Round,1149595,2024-03-01T00:30:00+00:00,319.0,Estadio Monumental David Arellano,Santiago de Chile,2315,Colo Colo,0,0,0,439,Godoy Cruz,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,13,CONMEBOL Libertadores,2024,Semi-finals,1308770,2024-10-23T00:30:00+00:00,21427.0,Arena MRV,"Belo Horizonte, Minas Gerais",1062,Atletico-MG,1,2,3,435,River Plate,0,0,0
145,13,CONMEBOL Libertadores,2024,Semi-finals,1308771,2024-10-24T00:30:00+00:00,218.0,Estádio Nilton Santos,Rio de Janeiro,120,Botafogo,0,5,5,2348,Penarol,0,0,0
146,13,CONMEBOL Libertadores,2024,Semi-finals,1308772,2024-10-30T00:30:00+00:00,19570.0,Estadio Mâs Monumental,"Capital Federal, Ciudad de Buenos Aires",435,River Plate,0,0,0,1062,Atletico-MG,0,0,0
147,13,CONMEBOL Libertadores,2024,Semi-finals,1308773,2024-10-31T00:30:00+00:00,1624.0,Estadio Centenario,Montevideo,2348,Penarol,1,2,3,120,Botafogo,0,1,1
148,13,CONMEBOL Libertadores,2024,Final,1314251,2024-11-30T20:00:00+00:00,19570.0,Estadio Mâs Monumental,"Capital Federal, Ciudad de Buenos Aires",1062,Atletico-MG,0,1,1,120,Botafogo,2,1,3

In [31]:
df_23

,competition_id,competition_name,competition_season,competition_round,fixture_id,fixture_date,fixture_venue_id,fixture_venue_name,fixture_venue_city,home_team_id,home_team_name,home_team_h1_goals,home_team_h2_goals,home_team_ft_goals,away_team_id,away_team_name,away_team_h1_goals,away_team_h2_goals,away_team_ft_goals
0,13,CONMEBOL Libertadores,2023,2nd Round,981590,2023-02-22T00:00:00+00:00,319.0,Estadio Monumental David Arellano,Santiago de Chile,2316,Curico Unido,0,0,0,1176,Cerro Porteno,0,1,1
1,13,CONMEBOL Libertadores,2023,2nd Round,981591,2023-02-27T22:00:00+00:00,1214.0,Estadio General Pablo Rojas,Asunción,1176,Cerro Porteno,0,1,1,2316,Curico Unido,0,0,0
2,13,CONMEBOL Libertadores,2023,2nd Round,981592,2023-02-23T00:30:00+00:00,1653.0,Estadio Olímpico de la UCV,Caracas,2810,Carabobo FC,0,0,0,1062,Atletico-MG,0,0,0
3,13,CONMEBOL Libertadores,2023,2nd Round,981593,2023-03-02T00:30:00+00:00,234.0,Estádio Governador Magalhães Pinto,"Belo Horizonte, Minas Gerais",1062,Atletico-MG,2,1,3,2810,Carabobo FC,1,0,1
4,13,CONMEBOL Libertadores,2023,2nd Round,981594,2023-02-22T22:00:00+00:00,337.0,Estadio El Teniente,Rancagua,2336,Magallanes,1,2,3,3700,Always Ready,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,13,CONMEBOL Libertadores,2023,Quarter-finals,1115603,2023-09-01T00:30:00+00:00,11622.0,Estadio Defensores del Chaco,Asunción,1182,Olimpia,1,0,1,124,Fluminense,1,2,3
145,13,CONMEBOL Libertadores,2023,Quarter-finals,1115604,2023-08-24T00:30:00+00:00,46.0,Estadio Alberto José Armando,Ciudad de Buenos Aires,451,Boca Juniors,0,0,0,436,Racing Club,0,0,0
146,13,CONMEBOL Libertadores,2023,Semi-finals,1125015,2023-09-29T00:30:00+00:00,46.0,Estadio Alberto José Armando,Ciudad de Buenos Aires,451,Boca Juniors,0,0,0,121,Palmeiras,0,0,0
147,13,CONMEBOL Libertadores,2023,Semi-finals,1125289,2023-09-28T00:30:00+00:00,NaN,Estádio do Maracanã,Rio de Janeiro,124,Fluminense,1,1,2,119,Internacional,1,1,2
148,13,CONMEBOL Libertadores,2023,Semi-finals,1125290,2023-10-05T00:30:00+00:00,244.0,Estádio José Pinheiro Borda,"Porto Alegre, Rio Grande do Sul",119,Internacional,1,0,1,124,Fluminense,0,2,2

In [48]:
# lets do one super code
LEAGUE_IDS = [13,11,773]
SEASONS = [2019,2020,2021,2022,2023,2024,2025]
STATUS   = "FT" #,"AET","PEN")

# ——— CONFIG ———
API_KEY    = FB_API_KEY
BASE_URL   = "https://v3.football.api-sports.io/fixtures"
HEADERS = {
    "Accept":           "application/json",
    "x-apisports-key":  API_KEY,
}
# LEAGUE_ID  = 13     # e.g. Premier League
# SEASON     = 2021   # e.g. 2024
# Only completed ("FT","AET","PEN") + in‑progress ("1H","HT","2H","ET","BT","P")
# STATUS   = ("FT","AET","PEN")
CHUNK_SIZE = 20     # max fixture IDs per call :contentReference[oaicite:2]{index=2}

In [49]:
def chunk_list(lst, size):
    """Split list into chunks of at most `size`."""
    return [lst[i:i+size] for i in range(0, len(lst), size)]

def fetch_fixture_ids(league_id, season):
    """Return a list of fixture IDs for the given league/season/status."""
    params = {
        "league": league_id,
        "season": season,
        "status": STATUS
    }
    resp = requests.get(BASE_URL, headers=HEADERS, params=params)
    print(f'running league_id = {league} for season {season}', resp.status_code, resp.headers.get("content-type"))
    #print(resp.text)
    resp.raise_for_status()
    fixtures = resp.json().get("response", [])
    return [f["fixture"]["id"] for f in fixtures if "fixture" in f]

def fetch_fixtures_by_ids(id_group):
    """Fetch full fixture data for a hyphen‑joined group of IDs."""
    ids_param = "-".join(str(i) for i in id_group)
    resp = requests.get(
        BASE_URL,
        headers=HEADERS,
        params={"ids": ids_param}
    )
    resp = requests.get(BASE_URL, headers=HEADERS, params={"ids": ids_param})
    print(resp.status_code, resp.request.url)
    #print(resp.text)   # or resp.json()
    resp.raise_for_status()
    return resp.json().get("response", [])

In [52]:
output_list = []

for league in LEAGUE_IDS:
    loop_list = []
    for season in SEASONS:
        fixture_ids = fetch_fixture_ids(league, season)
        chunks = chunk_list(fixture_ids, CHUNK_SIZE)
        print(f"Will retrieve {len(fixture_ids)} fixtures in {len(chunks)} batches.")

        
        for group in chunks:
            batch = fetch_fixtures_by_ids(group)
            loop_list.extend(batch)
            time.sleep(1)  # crude rate‑limit guard; adjust as needed :contentReference[oaicite:3]{index=3}
    output_list.extend(loop_list)
    
print(f"Retrieved detailed data for {len(output_list)} fixtures.")
        
# Then process with the earlier dict-based extraction
df_rows = []

for match in output_list:
    row = {
        'competition_id': match['league']['id'],
        'competition_name': match['league']['name'],
        'competition_season': match['league']['season'],
        'competition_round': match['league']['round'],
        'fixture_id': match['fixture']['id'],
        'fixture_date': match['fixture']['date'],
        'fixture_venue_id': match['fixture']['venue']['id'],
        'fixture_venue_name': match['fixture']['venue']['name'],
        'fixture_venue_city': match['fixture']['venue']['city'],
        'home_team_id': match['teams']['home']['id'],
        'home_team_name': match['teams']['home']['name'],
        'home_team_h1_goals': match['score']['halftime']['home'],
        'home_team_h2_goals': match['score']['fulltime']['home'] - match['score']['halftime']['home'],
        'home_team_ft_goals': match['score']['fulltime']['home'],
        'away_team_id': match['teams']['away']['id'],
        'away_team_name': match['teams']['away']['name'],
        'away_team_h1_goals': match['score']['halftime']['away'],
        'away_team_h2_goals': match['score']['fulltime']['away'] - match['score']['halftime']['away'],
        'away_team_ft_goals': match['score']['fulltime']['away']
    }
    df_rows.append(row)

complete_df =  pd.DataFrame(df_rows)

running league_id = 13 for season 2019 200 application/json
Will retrieve 151 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=241341-241343-241345-241344-241342-241346-241325-241327-241329-241333-241331-241337-241335-241339-241326-241332-241330-241328-241338-241334
200 https://v3.football.api-sports.io/fixtures?ids=241340-241317-241319-241321-241323-241318-241320-241322-241222-241221-241223-241225-241224-241226-241228-241227-241229-241233-241232-241230
200 https://v3.football.api-sports.io/fixtures?ids=241231-241234-241235-241236-241237-241239-241238-241241-241240-241242-241244-241243-241245-241248-241246-241247-241249-241250-241251-241252
200 https://v3.football.api-sports.io/fixtures?ids=241254-241253-241255-241258-241256-241257-241259-241260-241261-241264-241265-241262-241263-241266-241267-241268-241270-241269-241271-241272
200 https://v3.football.api-sports.io/fixtures?ids=241273-241276-241274-241275-241277-241278-241280-241281-241279-241282-241283-241284-241285-241287-241286-241288-241290-241289-241292-241291
200 https://v3.football.api-sports.io/fixtures?ids=241293-241297-241295-241294-241296-241298-241299-241300-241301-241302-241303-241304-241305-241307-241306-241308-241309-241310-241312-241311
200 https://v3.football.api-sports.io/fixtures?ids=241314-241313-241315-241316-241205-241207-241209-241213-241211-241217-241215-241219-241208-241210-241212-241214-241218-241220-241197-241199
200 https://v3.football.api-sports.io/fixtures?ids=241201-241203-241198-241200-241202-241204-241193-241195-241194-241196-247587
running league_id = 13 for season 2020 200 application/json
Will retrieve 150 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=293357-315948-293359-293358-315949-293360-318438-293354-293670-293352-321824-321826-315946-321828-318439-293355-293356-321825-293353-321827
200 https://v3.football.api-sports.io/fixtures?ids=321829-327202-327206-327204-327208-327205-327207-327209-327654-293292-293294-327655-293290-293297-293300-327656-315940-293291-293293-293299
200 https://v3.football.api-sports.io/fixtures?ids=327657-293295-293298-293296-293303-293301-293311-327659-327658-293308-293310-293305-315941-293309-327660-293302-293304-293307-327661-293306
200 https://v3.football.api-sports.io/fixtures?ids=293316-315942-293314-293321-327662-293318-327663-293312-293322-293317-293313-293319-327665-327664-293320-293315-293666-327666-293338-293333
200 https://v3.football.api-sports.io/fixtures?ids=293340-293341-293336-293335-293339-327667-293667-327668-293337-327669-293334-315943-293351-293345-315944-293668-327670-293349-293350-293346
200 https://v3.football.api-sports.io/fixtures?ids=327671-293342-293348-327672-293347-327673-293344-293343-293325-293326-293330-293331-315945-293327-293328-293329-293332-293323-327674-327675
200 https://v3.football.api-sports.io/fixtures?ids=293324-293669-327677-327676-644084-644085-644086-644088-644087-644090-644091-644093-644092-644096-644089-644097-644099-649953-649955-649957
200 https://v3.football.api-sports.io/fixtures?ids=649954-649956-651217-649958-651218-653384-654552-653385-654553-656970
running league_id = 13 for season 2021 200 application/json
Will retrieve 152 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=677592-674890-674892-677593-674891-674893-679774-679776-677588-682144-682977-677590-682146-682148-679775-679777-677589-682978-682145-677591
200 https://v3.football.api-sports.io/fixtures?ids=682147-682149-685882-685886-685884-685811-685883-685812-685887-685885-698305-697016-697018-697019-697014-697023-697012-697020-698306-697022
200 https://v3.football.api-sports.io/fixtures?ids=697017-697013-697015-697021-698307-699221-697032-697035-697033-697026-698308-698309-697024-697034-698310-699222-697028-697027-697025-697030
200 https://v3.football.api-sports.io/fixtures?ids=697031-697029-698311-697047-697044-697036-697039-697045-697042-698312-697038-697041-697043-698313-697037-699223-697040-697046-698314-697050
200 https://v3.football.api-sports.io/fixtures?ids=697051-698315-697056-697053-697055-697054-697052-699224-697059-697048-698316-697057-697058-697049-697060-697067-698317-699225-697066-698318
200 https://v3.football.api-sports.io/fixtures?ids=697069-697065-697068-697064-697071-697070-697061-698319-697063-697062-697076-699226-697078-697077-697082-697083-697073-697074-697075-698320
200 https://v3.football.api-sports.io/fixtures?ids=697079-698321-697072-698322-697081-697080-706481-706483-706485-706489-706487-706493-706491-706495-706486-706488-706490-706492-706494-706484
200 https://v3.football.api-sports.io/fixtures?ids=741527-747948-741529-760387-741528-747949-741530-760388-774978-793122-774979-793123
running league_id = 13 for season 2022 200 application/json
Will retrieve 149 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=819350-819348-819352-819351-819353-819340-819344-842760-828392-819342-842762-819346-842764-819341-842761-828393-819343-819347-842763-842765
200 https://v3.football.api-sports.io/fixtures?ids=846333-846336-846331-846335-846334-846337-853677-853676-853675-853679-853678-853680-853682-853683-853681-853685-853686-853684-853687-853688
200 https://v3.football.api-sports.io/fixtures?ids=853689-853690-853691-853692-853693-853694-853696-853695-853697-853698-853702-853699-853701-853700-853703-853704-853705-853706-853709-853710
200 https://v3.football.api-sports.io/fixtures?ids=853708-853707-853712-853713-853711-853714-853718-853716-853715-853717-853719-853720-853721-853722-853723-853724-853725-853728-853727-853726
200 https://v3.football.api-sports.io/fixtures?ids=853729-853730-853731-853733-853732-853734-853735-853736-853737-853738-853740-853741-853739-853743-853742-853744-853745-853746-853749-853747
200 https://v3.football.api-sports.io/fixtures?ids=853750-853748-853751-853752-853753-853754-853756-853755-853757-853759-853758-853760-853761-853762-853763-853764-853766-853765-853767-853768
200 https://v3.football.api-sports.io/fixtures?ids=853770-853769-863097-863103-863107-863101-863099-863095-863093-863105-863098-863108-863100-863102-863094-863096-863106-885347-885349-885351
200 https://v3.football.api-sports.io/fixtures?ids=885345-885348-885350-885346-933774-933776-933775-933777-958842
running league_id = 13 for season 2023 200 application/json
Will retrieve 149 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=981600-981602-981604-981601-981603-981605-1005140-1005511-981590-981594-1005513-981592-981598-981596-981591-1005514-1005141-981595-1005512-981593
200 https://v3.football.api-sports.io/fixtures?ids=981597-981599-1011462-1011466-1011464-1011460-1011463-1011467-1011465-1011461-1019262-1019264-1019263-1019265-1019266-1019267-1019268-1019270-1019269-1019272
200 https://v3.football.api-sports.io/fixtures?ids=1019271-1019273-1019275-1019274-1019277-1019276-1019278-1019279-1019282-1019281-1019280-1019283-1019284-1019286-1019287-1019288-1019285-1019289-1019290-1019292
200 https://v3.football.api-sports.io/fixtures?ids=1019291-1019293-1019295-1019294-1019296-1019298-1019297-1019299-1019300-1019301-1019302-1019303-1019304-1019305-1019307-1019306-1019308-1019309-1019311-1019310
200 https://v3.football.api-sports.io/fixtures?ids=1019314-1019313-1019312-1019315-1019325-1019316-1019318-1019319-1019320-1019321-1019317-1019322-1019324-1019323-1019326-1019327-1019328-1019330-1019329-1019331
200 https://v3.football.api-sports.io/fixtures?ids=1019332-1019338-1019333-1019336-1019335-1019334-1019337-1019339-1019340-1019341-1019342-1019343-1019345-1019344-1019347-1019346-1019349-1019348-1019351-1019352
200 https://v3.football.api-sports.io/fixtures?ids=1019350-1019353-1019354-1019355-1019356-1019357-1052189-1052187-1052185-1052181-1052179-1052183-1052191-1052177-1052190-1052182-1052184-1052178-1052192-1115294
200 https://v3.football.api-sports.io/fixtures?ids=1115604-1115296-1115602-1115295-1115297-1115603-1125289-1125015-1125290
running league_id = 13 for season 2024 200 application/json
Will retrieve 149 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=1149600-1149602-1149604-1149603-1149605-1149598-1149590-1149592-1174580-1174742-1174582-1149596-1149594-1149599-1149593-1174581-1174583-1174743-1149597-1149595
200 https://v3.football.api-sports.io/fixtures?ids=1178191-1178189-1180019-1178193-1178190-1180020-1187186-1187185-1187187-1187188-1187189-1187191-1187192-1187190-1187193-1187194-1187195-1187197-1187196-1187199
200 https://v3.football.api-sports.io/fixtures?ids=1187200-1187198-1187202-1187201-1187204-1187203-1187205-1187208-1187206-1187207-1187209-1187211-1187210-1187212-1187214-1187213-1187215-1187216-1187217-1187218
200 https://v3.football.api-sports.io/fixtures?ids=1187219-1187220-1187221-1187222-1187223-1187225-1187224-1187228-1187226-1187227-1187230-1187229-1187231-1187232-1187234-1187233-1187236-1187235-1187237-1187238
200 https://v3.football.api-sports.io/fixtures?ids=1187240-1187241-1187242-1187243-1187244-1187245-1187246-1187247-1187248-1187249-1187250-1187251-1187252-1187253-1187255-1187254-1187257-1187259-1187258-1187261
200 https://v3.football.api-sports.io/fixtures?ids=1187260-1187264-1187263-1187262-1187267-1187265-1187266-1187268-1187270-1187269-1187272-1187271-1187274-1187275-1187276-1187273-1187278-1187277-1187279-1187280
200 https://v3.football.api-sports.io/fixtures?ids=1187239-1187256-1203724-1202193-1202199-1203722-1202203-1202201-1202195-1202197-1202194-1202200-1203723-1202204-1202202-1202196-1202198-1294401-1294399-1295064
200 https://v3.football.api-sports.io/fixtures?ids=1295066-1294402-1294400-1295067-1308770-1308771-1308772-1308773-1314251
running league_id = 13 for season 2025 200 application/json
Will retrieve 107 fixtures in 6 batches.
200 https://v3.football.api-sports.io/fixtures?ids=1325649-1325647-1327684-1325650-1325648-1325641-1350680-1327682-1325645-1350682-1325643-1350298-1327868-1327683-1325646-1325644-1350683-1350299-1327869-1355039
200 https://v3.football.api-sports.io/fixtures?ids=1355636-1355043-1355041-1355040-1355637-1355044-1355042-1361868-1361856-1361865-1361864-1361858-1361862-1361871-1361870-1361863-1361857-1361859-1361867-1361866
200 https://v3.football.api-sports.io/fixtures?ids=1361860-1361869-1361861-1361873-1361878-1361887-1361875-1361872-1361874-1361886-1361883-1361885-1361877-1361884-1361876-1361882-1361881-1361880-1361879-1361892
200 https://v3.football.api-sports.io/fixtures?ids=1361895-1361889-1361898-1361896-1361891-1361902-1361903-1361888-1361890-1361894-1361897-1361893-1361900-1361899-1361901-1361967-1361965-1361959-1361966-1361973
200 https://v3.football.api-sports.io/fixtures?ids=1361969-1361962-1361958-1361963-1361971-1361970-1361972-1361964-1361968-1361961-1361960-1361979-1361983-1361975-1361987-1361989-1361985-1361988-1361974-1361980
200 https://v3.football.api-sports.io/fixtures?ids=1361982-1361977-1361986-1361981-1361984-1361978-1361976
running league_id = 11 for season 2019 200 application/json
Will retrieve 92 fixtures in 5 batches.
200 https://v3.football.api-sports.io/fixtures?ids=241059-241061-241063-241065-241067-241069-241071-241073-241060-241062-241064-241066-241068-241075-241070-241077-241081-241079-241085-241083
200 https://v3.football.api-sports.io/fixtures?ids=241076-241087-241089-241091-241093-241097-241095-241099-241101-241082-241088-241096-241098-241100-241027-241029-241031-241033-241035-241037
200 https://v3.football.api-sports.io/fixtures?ids=241039-241043-241041-241047-241045-241049-241051-241053-241055-241057-241046-241030-241034-241028-241036-241042-241040-241044-241054-241032
200 https://v3.football.api-sports.io/fixtures?ids=241048-241050-241056-241052-241058-241011-241013-241015-241012-241014-241017-241019-241021-241023-241025-241018-241020-241022-241026-241024
200 https://v3.football.api-sports.io/fixtures?ids=241003-241005-241004-241006-241007-241009-241008-241010-240999-241001-241000-245836
running league_id = 11 for season 2020 200 application/json
Will retrieve 102 fixtures in 6 batches.
200 https://v3.football.api-sports.io/fixtures?ids=293256-321811-293280-293273-293265-293271-321813-293267-321815-293261-321817-293278-293259-293277-293269-293275-293283-293264-293289-321820
200 https://v3.football.api-sports.io/fixtures?ids=293286-293284-293281-293257-293274-293268-293272-321814-321816-321818-293262-293266-293260-293270-321819-293279-293263-293288-293282-293276
200 https://v3.football.api-sports.io/fixtures?ids=293258-293287-293285-644303-644302-644304-644305-644307-644306-644308-644310-644311-644309-644312-644313-644314-644315-644316-644317-644318
200 https://v3.football.api-sports.io/fixtures?ids=644319-644320-644321-644322-644324-644323-644327-644326-644328-644329-644333-644330-644332-644331-645896-645636-645635-645890-645892-645894
200 https://v3.football.api-sports.io/fixtures?ids=645637-645898-645897-645640-645639-645893-645891-645638-645895-650125-650127-650129-650131-650126-650128-650130-650132-653218-653220-653219
200 https://v3.football.api-sports.io/fixtures?ids=653221-657639
running league_id = 11 for season 2021 200 application/json
Will retrieve 156 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=674870-674878-674886-683012-674868-674866-674874-674884-674888-674872-674882-674876-683014-674880-674871-674887-683013-692868-692870-674875
200 https://v3.football.api-sports.io/fixtures?ids=674869-674867-674885-674889-674873-674883-674877-683015-674881-692869-692871-697087-697091-697092-697088-697090-698685-698686-697089-697086
200 https://v3.football.api-sports.io/fixtures?ids=698687-697085-697084-699237-698688-697093-698136-697095-697096-697094-697097-698690-698689-697102-697101-697098-698137-697099-699238-698692
200 https://v3.football.api-sports.io/fixtures?ids=698691-697103-697100-697105-697107-697108-697110-697104-698693-699239-697112-698695-697106-698694-698696-698138-697109-697113-697111-697121
200 https://v3.football.api-sports.io/fixtures?ids=697118-697122-698697-697116-697114-697120-698698-699240-698699-697123-697115-697117-698700-697119-698139-697125-698140-697131-698702-697132
200 https://v3.football.api-sports.io/fixtures?ids=697126-697128-697124-697127-699241-697130-698703-697129-697133-698705-698704-697140-698706-697142-697141-698701-697135-697139-697134-698707
200 https://v3.football.api-sports.io/fixtures?ids=698141-699242-697136-697138-697143-698708-697137-706464-706466-706468-706472-706470-706474-706476-706478-706465-706467-706469-706471-706473
200 https://v3.football.api-sports.io/fixtures?ids=706475-706479-706477-741614-741612-740326-741616-741615-741613-740327-741617-774976-774974-774977-774975-801513
running league_id = 11 for season 2022 200 application/json
Will retrieve 150 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=819362-819356-819354-819358-819360-819364-819366-819368-819370-819374-819372-819376-819380-819382-819384-819378-819363-819357-819355-819359
200 https://v3.football.api-sports.io/fixtures?ids=819361-819365-819369-819371-819375-819377-819381-819385-819379-819383-853849-853848-853847-853851-853850-853853-853854-853852-853856-853855
200 https://v3.football.api-sports.io/fixtures?ids=853857-853858-853859-853862-853861-853860-853863-853864-853865-853867-853866-853869-853870-853868-853872-853871-853875-853874-853873-853878
200 https://v3.football.api-sports.io/fixtures?ids=853876-853877-853880-853879-853883-853882-853881-853885-853886-853884-853887-853888-853890-853889-853892-853893-853891-853894-853896-853895
200 https://v3.football.api-sports.io/fixtures?ids=853898-853899-853897-853901-853902-853900-853904-853903-853907-853906-853905-853908-853909-853910-853912-853913-853911-853915-853916-853914
200 https://v3.football.api-sports.io/fixtures?ids=853918-853920-853919-853917-853921-853923-853922-853926-853924-853925-853927-853928-853929-853932-853930-853931-853935-853933-853934-853936
200 https://v3.football.api-sports.io/fixtures?ids=853937-853938-853939-853940-853941-853942-863635-863639-863643-863641-863633-863647-863645-863637-863636-863640-863644-863642-863648-863638
200 https://v3.football.api-sports.io/fixtures?ids=885353-885357-885359-885355-885354-885358-933926-933928-933927-959553
running league_id = 11 for season 2023 200 application/json
Will retrieve 149 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=981696-981702-981701-981698-981699-981700-981708-981707-981704-981706-981709-981710-981711-1019385-1019384-1019387-1019386-1019388-1019389-1019391
200 https://v3.football.api-sports.io/fixtures?ids=1019392-1019390-1019393-1019394-1019395-1019397-1019398-1019399-1019396-1019401-1019400-1019402-1019403-1019404-1019405-1019406-1019408-1019409-1019410-1019407
200 https://v3.football.api-sports.io/fixtures?ids=1019411-1019412-1019415-1019414-1019413-1019418-1019416-1019417-1019420-1019419-1019421-1019422-1019425-1019423-1019424-1019426-1019428-1019427-1019429-1019430
200 https://v3.football.api-sports.io/fixtures?ids=1019431-1019433-1019432-1019434-1019435-1019436-1019437-1019438-1019439-1019440-1019441-1019442-1019443-1019444-1019447-1019445-1019446-1019449-1019448-1019450
200 https://v3.football.api-sports.io/fixtures?ids=1019451-1019452-1019453-1019455-1019454-1019456-1019460-1019458-1019459-1019457-1019461-1019462-1019463-1019464-1019465-1019466-1019467-1019468-1019469-1019470
200 https://v3.football.api-sports.io/fixtures?ids=1019471-1019472-1019473-1019474-1019475-1019479-1019477-1019478-1019476-1046415-1046417-1046419-1046421-1046425-1046423-1046427-1046429-1046416-1046418-1046420
200 https://v3.football.api-sports.io/fixtures?ids=1046422-1046426-1046424-1046430-1046428-1092492-1081838-1081846-1081840-1081844-1081842-1081848-1092494-1092493-1081839-1081847-1081845-1081841-1081843-1115594
200 https://v3.football.api-sports.io/fixtures?ids=1115596-1115598-1115600-1115597-1115599-1125833-1125835-1125834-1125836
running league_id = 11 for season 2024 200 application/json
Will retrieve 147 fixtures in 8 batches.
200 https://v3.football.api-sports.io/fixtures?ids=1150512-1150510-1150509-1150514-1150516-1150520-1150513-1150521-1150519-1150517-1150515-1187091-1187090-1187092-1187089-1187093-1187095-1187094-1187098-1187097
200 https://v3.football.api-sports.io/fixtures?ids=1187096-1187099-1187100-1187102-1187101-1187103-1187104-1187106-1187105-1187108-1187109-1187107-1187111-1187110-1187113-1187112-1187114-1187115-1187116-1187117
200 https://v3.football.api-sports.io/fixtures?ids=1187118-1187119-1187120-1187121-1187123-1187122-1187124-1187125-1187127-1187126-1187128-1187129-1187130-1187131-1187132-1187133-1187134-1187135-1187136-1187138
200 https://v3.football.api-sports.io/fixtures?ids=1187137-1187139-1187141-1187142-1187143-1187145-1187144-1187147-1187146-1187148-1187149-1187150-1187152-1187151-1187153-1187154-1187155-1187156-1187157-1187160
200 https://v3.football.api-sports.io/fixtures?ids=1187159-1187158-1187162-1187161-1187163-1187165-1187167-1187166-1187168-1187170-1187169-1187173-1187172-1187174-1187171-1187175-1187176-1187180-1187177-1187179
200 https://v3.football.api-sports.io/fixtures?ids=1187178-1187181-1187182-1187183-1187184-1187140-1187164-1205346-1205344-1205348-1202641-1205350-1202645-1205352-1202643-1205345-1205349-1205351-1202642-1202646
200 https://v3.football.api-sports.io/fixtures?ids=1202644-1205353-1261158-1261152-1261156-1265732-1265730-1265728-1261160-1261154-1261159-1261157-1265733-1265731-1265729-1294586-1294588-1295060-1295062-1294587
200 https://v3.football.api-sports.io/fixtures?ids=1295063-1295061-1309265-1309266-1309267-1309268-1314355
running league_id = 11 for season 2025 200 application/json
Will retrieve 88 fixtures in 5 batches.
200 https://v3.football.api-sports.io/fixtures?ids=1326748-1327870-1326754-1333254-1327872-1326746-1326749-1326755-1362101-1362106-1362092-1362093-1362103-1362107-1362096-1362104-1362094-1362099-1362097-1362098

In [54]:
complete_df.to_csv("south_american_tourney_results.csv")